coffee:
  description: Make a coffee
  fields:
    brew_temp:
      required: true
      default: Medium
      selector:
        select:
          options:
            - Low
            - Medium
            - High
    brew_type:
      required: true
      default: Lungo
      selector:
        select:
          options:
            - Ristretto
            - Espresso
            - Lungo
            - Americano
            - label: Hot Water
              value: HOT_WATER

